Add support for Windows
ozanonurtek/flask-now pull request #6
Opened 2019-10-06 18:14 UTC by c-w

This pull request makes flask-now work on Windows.

![Animation showing flask-now running on Windows](https://user-images.githubusercontent.com/1086421/66273622-7848ca80-e843-11e9-8a08-65e3be805003.gif)

This required two minor fixes:

- The `which` utility doesn't exist on Windows which leads to a FileNotFoundError when trying to look up the path of the Python binary. This change adds a fallback to [sys.executable](https://docs.python.org/3/library/sys.html#sys.executable) which fixes the problem (as long as we can assume that the Python interpreter used to run flask-now is a valid Python3 interpreter).

- The path to the pip executable in a virtual environment is different on Windows than Unix which leads to a FileNotFoundError. This change adds a check to [os.name](https://docs.python.org/3/library/os.html#os.name) to adjust the pip path if flask-now is being run on Windows.

2019-10-06 19:28 UTC, ozanonurtek commented
Thanks for your contribution and opening this pull request,

- sys.executable also works fine with MacOS and Linux. I guess we don't need to check for operating system at the beginning of the main function. I would be appreciated if you could refactor your pull request in that way.
- install_extensions functions looks good!

2019-10-06 19:29 UTC, ozanonurtek requested changes
As I mentioned before,  sys.executable also works fine with MacOS and GNU/Linux. So could you please refactor your contribution in that way 😸

2019-10-06 21:33 UTC, c-w commented
Thanks for the review @ozanonurtek. Made the change to always use `sys.executable` in 763cba8.

2019-10-06 22:02 UTC, ozanonurtek approved these changes

2019-10-06 22:04 UTC, ozanonurtek commented
@c-w, thanks for the change!

2019-10-06 22:04 UTC, merged

2019-10-19 19:34 UTC, ozanonurtek commented
Released under 0.2.2. I was a bit busy, sorry for latency. Thanks for your all support @c-w 🎉